import "./globals.scss";
import Header from "./Header";
import Providers from "./Providers";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let res = cookies().get("mode");
  console.log(res)
  return (
    <html lang="en">
      <body>
        <Providers>
        <Header />
        {children}
        </Providers>
      </body>
    </html>
  );
}
